### ISSUE TITLE
Problems Compiling the webpart

### ISSUE THREAD

**Issue by NPrice99** [estruyf/Search-WP-SPFx#1]
Hi Elio
I followed your instructions in the ReadMe and got as far as gulp serve and got these errors 👎 

Error - typescript - node_modules\@microsoft\sp-module-loader\lib\SPModuleLoader.d.ts(1,28): error TS2307: Cannot find module 'combokeys'.
Error - typescript - node_modules\@microsoft\sp-module-loader\lib\importableSpModuleLoader.d.ts(1,28): error TS2307: Cannot find module 'combokeys'.
Error - typescript - src\webparts\searchSpfx\flux\dispatcher\appDispatcher.ts(1,23): error TS2307: Cannot find module 'flux'.
Error - 'typescript' sub task errored after 6.68 s
 "TypeScript error(s) occurred."

I have tried npm install -g combokeys  (and flux) 
I have tried npm install combokeys --save (and flux)
I have tried npm install combokeys --save-dev (and flux)

Both are in \Search-WP-SPFx\node_modules

All with no effect.  What am I doing wrong ?

Thanks

Nigel

**Comment by estruyf** [comment]
@NPrice99,

Known issue from the SharePoint Framework. Install it via `tsd install combokeys --save` for flux: `tsd install flux --save`

**Comment by NPrice99** [comment]
Hi Elio

Have done tsd install combokeys --save and tsd install flux --save

now get

[10:40:51] Error - typescript - typings\react\react-addons-test-utils.d.ts(98,26): error TS2314: Generic type 'DOMElement<P, T>' requires 2 type argument(s).
[10:40:51] Error - typescript - typings\react\react-dom.d.ts(14,22): error TS2314: Generic type 'DOMElement<P, T>' requires 2 type argument(s).
[10:40:51] Error - typescript - typings\react\react-dom.d.ts(36,26): error TS2314: Generic type 'DOMElement<P, T>' requires 2 type argument(s).

when enter gulp serve

version of React is 3.10.7

Regards

Nigel

**Comment by estruyf** [comment]
Lovely will try to reproduce. Maybe something with the React version of typings used in the SPFx.

**Comment by NPrice99** [comment]
Hi Elio

Fixed the problem -

tsd install react-global --save
tsd update --save --overwrite

which I found from here - http://stackoverflow.com/questions/27399365/how-to-compile-typescript-with-react-definitions

The file react-dom.d.ts got updated with the correct parameters during these two commands.

gulp serve now runs fine.

Regards

Nigel

**Comment by estruyf** [comment]
Great news! Will also do these steps and hopefully it never happens anymore :smile: 

Thanks!

**Comment by estruyf** [comment]
Was able to reproduce it. Followed your steps and should be fixed in the next pr.
