### ISSUE TITLE
Issue in searching 

### ISSUE THREAD

**Issue by himanjanpati** [estruyf/Search-WP-SPFx#3]
Hello,
Will it give the search result as soon as a document will be added to SharePoint or it will wait till the time the scheduled crawled in SPO then it will render the search result for the newly added items?

**Comment by estruyf** [comment]
Based on SharePoint search, so yes, it will have to wait until the crawler passes the document to get added or updated.

**Comment by himanjanpati** [comment]
@estruyf, thanks :)
